Ansible playbooks to deploy HA redis cluster

diff --git a/roles/redis_master/templates/twemproxy.upstart.j2 b/roles/redis_master/templates/twemproxy.upstart.j2
--- a/roles/redis_master/templates/twemproxy.upstart.j2
+++ b/roles/redis_master/templates/twemproxy.upstart.j2
@@ -1,107 +1,76 @@
 #!/bin/bash
 ### BEGIN INIT INFO
-# Provides: redis
-# Required-Start:	$syslog $remote_fs
-# Required-Stop:	$syslog $remote_fs
-# Should-Start:		$local_fs
-# Should-Stop:		$local_fs
+# Provides:		twemproxy
+# Required-Start:	$syslog $remote_rs
+# Required-Stop:	$syslog $remote_rs
+# Should-start:		$local_fs
+# Should-stop:		$local_fs
 # Default-Start:	2 3 4 5
-# Default-Stop:		0 1 6
-# Short-Description:		twemproxy - proxy for redis-server
-# Description:					twemproxy - proxy for redis-server
+# Default-Stop:		0 1 6	
+# Short-Description:	twemproxy - a redis proxy
+# Description:		twemproxy - a redis proxy
 ### END INIT INFO
 # Authored by Bean He
-# Version 1.0
+# Version 2.0
+#####################
 
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-cfg_dir={{ deploy_base }}/{{ proxy_name }}
-cfg_file=${cfg_dir}/settings.yml
-pid_dir=/var/run/twemproxy
-pid_file=${pid_dir}/twemproxy.pid
-log_dir=/var/log/twemproxy
-log_file=${log_dir}/twemproxy.log
-nutcracker={{ exec_dir }}/{{ proxy_name }}
+PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:{{ exec_dir }}
+DAEMON={{ exec_dir }}/{{ proxy_name }}
+NAME=nutcracker
+DESC=twemproxy
 
-if [ x"${nutcracker}" == x"" ];then
-	echo "Command 'nutcracker' not found ..."
-	exit 1
-fi
+RUNDIR=/var/run/twemproxy
+PIDFILE=$RUNDIR/nutcracker.pid
+LOGDIR=/var/log/twemproxy
+LOGFILE=$LOGDIR/nutcracker.log
+DAEMON_ARGS="-o $LOGFILE -c {{ deploy_base }}/{{ proxy_name }}/{{ proxy_name }}.yml -p $PIDFILE"
 
-if [ ! -d ${cfg_dir} ];then
-	mkdir -p ${cfg_dir}
-fi
+test -x $DAEMON || exit 0
 
-if [ ! -d ${pid_dir} ];then
-	mkdir -p ${pid_dir}
-fi
+set -e
 
-if [ ! -d ${log_dir} ];then
-	mkdir -p ${log_dir}
-fi
-
-
-START(){
-	touch ${pid_file}
-	if [ ! -s ${pid_file} ];then
-		${nutcracker} -d -o ${log_file} -p ${pid_file} -c ${cfg_file}
-		sleep 1
-		`which pidof` nutcracker > ${pid_file}
-		if [ -s ${pid_file} ];then
-			echo -e "Start running \e[32m[OK]\e[0m, PID: $(cat ${pid_file})"
-		else
-			echo -e "Start running \e[31m[Failed]\e[0m"
-			return 1
-		fi
-	else
-		echo "Already running, PID: $(cat ${pid_file})"
-		return 0
-	fi
-}
-
-STOP(){
-	pid=`cat ${pid_file}`
-	if [ -s ${pid_file} ];then
-		if  ps -ef | awk '{print $2}' | grep -v grep | grep -qw ${pid} ;then
-			kill -9 ${pid} > /dev/null
-			if [ $? -eq 0 ];then
-				echo -e "Stop running \e[32m[OK]\e[0m"
-				> ${pid_file}
-			else
-				echo -e "Stop running \e[31m[Failed]\e[0m"
-				return 1
-			fi
-		else
-			echo "Already stopped ..."
-			> ${pid_file}
-		fi
-	else
-		echo "Already stopped ..."
-	fi
-}
-
-STATUS(){
-	pid=`cat ${pid_file}`
-	if [ -s ${pid_file} ];then
-		echo -e "Already running, PID: ${pid}"
-	else
-		echo -e "Already stopped ..."
-	fi
-}
-
-case $1 in
+case "$1" in
 	start)
-		START
+	echo -n "Starting $DESC: "
+	mkdir -p $RUNDIR
+	touch $PIDFILE
+	chown redis:redis $RUNDIR $PIDFILE $LOGDIR $LOGFILE
+	chmod 755 $RUNDIR
+	if start-stop-daemon --start --quiet --umask 007  --exec $DAEMON -- $DAEMON_ARGS &
+	then
+		echo "$NAME."
+	else
+		echo "failed"
+	fi
 	;;
 	stop)
-		STOP
+	echo -n "Stopping $DESC: "
+	if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
+	then
+		echo "$NAME."
+	else
+		echo "failed"
+	fi
+	rm -f $PIDFILE
+	;;
+	restart|force-reload)
+	${0} stop
+	${0} start
 	;;
 	status)
-		STATUS
-	;;
-	restart)
-		STOP && START
+	echo -n "$DESC is "
+	if start-stop-daemon --stop --quiet --signal 0 --name $NAME --pidfile $PIDFILE
+	then
+		echo "running"
+	else
+		echo "not running"
+		exit 1
+	fi
 	;;
 	*)
-		echo "Usage: $0 {start|stop|status|restart}"
+	echo "Usage: /etc/init.d/$DESC {start|stop|restart|force-reload}" >&2
+	exit 1
 	;;
 esac
+
+exit 0
